### ISSUE TITLE
CORB execution does not work with xcc.httpcompliant=true

### ISSUE THREAD

**Issue by tzejohn** [marklogic/corb2#43] opened 2016-11-22 14:13 UTC
I have an Amazon ELB setup in front of a cluster of ML nodes. MLCP and mlGradle tasks work fine deploying to this load balancer as long as I set the `xcc.httpcompliant` flag to `true`. When I attempt the same when I execute `com.marklogic.developer.corb.Manager`, I get a BAD_REQUEST error.

```
SEVERE: Error while running CORB
com.marklogic.developer.corb.CorbException: While invoking Uris Module
	at com.marklogic.developer.corb.QueryUrisLoader.open(QueryUrisLoader.java:180)
	at com.marklogic.developer.corb.Manager.populateQueue(Manager.java:710)
	at com.marklogic.developer.corb.Manager.run(Manager.java:494)
	at com.marklogic.developer.corb.Manager.main(Manager.java:143)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: com.marklogic.xcc.exceptions.ServerResponseException: Module spawn request rejected (400, BAD_REQUEST). Is this an XDBC server?
 [Session: user=admin, cb={default} [ContentSource: user=admin, cb={none} [provider: address=internal-ml-cluster-irx-dev-lb-1031654958.us-east-1.elb.amazonaws.com/10.239.12.224:8050, pool=0/64]]]
 [Client: XCC/8.0-5]
	at com.marklogic.xcc.impl.handlers.NotFoundCodeHandler.handleResponse(NotFoundCodeHandler.java:39)
	at com.marklogic.xcc.impl.handlers.EvalRequestController.serverDialog(EvalRequestController.java:96)
	at com.marklogic.xcc.impl.handlers.AbstractRequestController.runRequest(AbstractRequestController.java:88)
	at com.marklogic.xcc.impl.SessionImpl.submitRequestInternal(SessionImpl.java:437)
	at com.marklogic.xcc.impl.SessionImpl.submitRequest(SessionImpl.java:432)
	at com.marklogic.developer.corb.QueryUrisLoader.open(QueryUrisLoader.java:130)
	... 8 more
```

Is this compliance mode flag being ignored? I would see similar errors using MLCP if the flag was not set.

**Comment by tzejohn** [comment] 2016-11-22 14:16
It works fine if I just specify one of the nodes directly, instead of going through the ELB.

**Comment by rjkennedy98** [comment] 2016-11-22 14:16
Use the TCP listener with ELB. The HTTP listener will not work.

Also MLCP should not go over the load balancer. It should point directly to
a node as it load balances itself.

**Comment by tzejohn** [comment] 2016-11-22 14:23
@rjkennedy98 if I use the TCP protocol, then I won't be able to configure any session stickiness, as that is HTTP specific. I have had no other issues with xcc protocol up until now. Are you saying the `xcc.httpcompliant` flag should never be used?

**Comment by rjkennedy98** [comment] 2016-11-22 14:42
Here is a link to the documentation we have.
https://help.marklogic.com/knowledgebase/article/View/32/15/load-balancing-in-marklogic <https://help.marklogic.com/knowledgebase/article/View/32/15/load-balancing-in-marklogic>
"In previous releases of MarkLogic server, XCC applications were not supported with HTTP load balancer. However, since MarkLogic 7, it is now possible to run XCC applications against a Layer 3 HTTP load balancer. “ The closest to that is the TCP listener in ELB.

I’m not sure about session stickiness. Perhaps someone else can comment on that. I could be wrong but I thought that you’d only need session stickiness if you were running queries that needed to repeatedly hit the same server such as multi statement transactions. I’m not sure its needed for CORB. Hopefully someone else can clarify that.

Richard

**Comment by bbandlamudi** [comment] 2016-11-22 15:41
Could you please register to corb2 mailing list http://developer.marklogic.com/mailman/listinfo/corb2? It is generally quicker to get response from multiple people and not just us who monitor the issues. 

How are you setting the xcc.httpcompliant to xcc connection? Are you using the java vm argument "-Dxcc.httpcompliant=true" to the java command that starts CORB? Please note that xcc is a wapper around http, so http complaince should work on xcc/xdbc connections. Please look into the section http://docs.marklogic.com/7.0/guide/xcc/concepts#id_85598 for helping with configuring load balancers for xcc. 

Having said, are you using multi-statement transactions in your selector query? We use F5 load balancers quite a bit and we generally do not need to explicitly set http complains as single statement transactions generally do not require it. 

Thanks,
Bhagat

**Comment by tzejohn** [comment] 2016-11-22 18:11
@bbandlamudi I am using the `-Dxcc.httpcompliant=true` in the VM arguments.  As I mentioned, this same flag work for other tasks that leverage XCC, like MLCP and mlGradle deployment tasks.

I am just running a simple CORB job where in my URIS-MODULE I am pulling back the uris in a specific collection, and in the PROCESS-MODULE, I modify the document structure. Looking at the error trace, it looks like it has not even started to execute anything. Just communicating with the endpoint is failing.

**Comment by bbandlamudi** [comment] 2016-11-22 19:50
Closing the issue as TJ has confirmed that xcc code snippet and corb manager worked fine in further testing. We can continue the conversation on corb2 email reflector and re-open the issue if we there is in fact an issue.

**Closed by bbandlamudi** 2016-11-22 19:50 UTC
