### ISSUE TITLE
Invalid TLS padding data

### ISSUE THREAD

**Issue by rjkennedy98** [marklogic/corb2#28] opened 2016-06-15 17:00 UTC
I was asked to file this as a Corb issue by Support. We are using:
MarkLogic version – 8.0-5.2
XCC Version – 8.0-4.2
CORB2 Version – 2.2.0

com.marklogic.developer.corb.CorbException: While invoking Uris Module
at com.marklogic.developer.corb.QueryUrisLoader.open(QueryUrisLoader.java:152)
at com.marklogic.developer.corb.Manager.populateQueue(Manager.java:560)
at com.marklogic.developer.corb.Manager.run(Manager.java:346)
at com.marklogic.developer.corb.extension.RestartManager.main(RestartManager.java:65)
Caused by: com.marklogic.xcc.exceptions.ServerConnectionException: Error parsing HTTP headers: Invalid TLS padding data
[Session: user=s020499, cb={default} [ContentSource: user=xxxxxxx, cb={none} [provider: SSLconn address=xxxx.xxxx.xxxxx.xxxx.com/xx.xx.xx.xx:443, pool=2/64]]]
[Client: XCC/8.0-1]
at com.marklogic.xcc.impl.handlers.AbstractRequestController.runRequest(AbstractRequestController.java:125)
at com.marklogic.xcc.impl.SessionImpl.submitRequestInternal(SessionImpl.java:437)
at com.marklogic.xcc.impl.SessionImpl.submitRequest(SessionImpl.java:432)
at com.marklogic.developer.corb.QueryUrisLoader.open(QueryUrisLoader.java:131)
... 3 more
Caused by: java.io.IOException: Error parsing HTTP headers: Invalid TLS padding data
at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1714)
at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:968)
at sun.security.ssl.SSLEngineImpl.readNetRecord(SSLEngineImpl.java:893)
at sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:767)
at javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:624)
at com.marklogic.io.SslByteChannel.unwrapNetData(SslByteChannel.java:449)
at com.marklogic.io.SslByteChannel.fillBufferFromEngineInsideHandshake(SslByteChannel.java:229)
at com.marklogic.io.SslByteChannel.readInsideHandshake(SslByteChannel.java:213)
at com.marklogic.io.SslByteChannel.handleHandshake(SslByteChannel.java:408)
at com.marklogic.io.SslByteChannel.fillBufferFromEngine(SslByteChannel.java:198)
at com.marklogic.io.SslByteChannel.read(SslByteChannel.java:143)
at com.marklogic.http.HttpChannel$ChannelInputStream.timedRead(HttpChannel.java:501)
at com.marklogic.http.HttpChannel$ChannelInputStream.fillBuffer(HttpChannel.java:489)
at com.marklogic.http.HttpChannel$ChannelInputStream.read(HttpChannel.java:448)
at com.marklogic.http.HttpChannel$ChannelInputStream.read(HttpChannel.java:468)
at com.marklogic.http.HttpHeaders.nextHeaderLine(HttpHeaders.java:313)
at com.marklogic.http.HttpHeaders.parseResponseHeaders(HttpHeaders.java:272)
at com.marklogic.http.HttpChannel.parseHeaders(HttpChannel.java:321)
at com.marklogic.http.HttpChannel.receiveMode(HttpChannel.java:294)
at com.marklogic.http.HttpChannel.getResponseCode(HttpChannel.java:193)
at com.marklogic.xcc.impl.handlers.EvalRequestController.serverDialog(EvalRequestController.java:76)
at com.marklogic.xcc.impl.handlers.AbstractRequestController.runRequest(AbstractRequestController.java:87)
... 6 more
Caused by: javax.net.ssl.SSLHandshakeException: Invalid TLS padding data
... 29 more
Caused by: javax.crypto.BadPaddingException: Invalid TLS padding data
at sun.security.ssl.CipherBox.removePadding(CipherBox.java:692)
at sun.security.ssl.CipherBox.decrypt(CipherBox.java:423)
at sun.security.ssl.InputRecord.decrypt(InputRecord.java:154)
at sun.security.ssl.EngineInputRecord.decrypt(EngineInputRecord.java:192)
at sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:962)
... 26 more

**Comment by hansenmc** [comment] 2016-06-16 01:45
This would indicate a lower-level issue, possibly an issue with XCC, and not necessarily a CORB issue/bug.  Unless you would want CORB to handle the exception differently, such as retry when the exception is thrown. 

Is this a repeatable error? Does this error occur every time, or only occasionally? Have you tried with the latest XCC 8.0.5?

**Comment by rjkennedy98** [comment] 2016-06-16 15:17
@hansenmc Yes, I agree its an XCC issue. I'm not able to recreate the error myself. It gets throw intermittently in all our environments, but I'm not sure if its because of a particular data condition or if its something transient like a network issue. Without being able to recreate it, its hard for us to test with another version of XCC. We run more than tens of thousand CORB jobs per day in our production environment and we see maybe 4 of these errors. 

We are happy with the way CORB handles this, this issue was filed per Support's request and I am fine if you want to close it out.

**Comment by bbandlamudi** [comment] 2016-06-16 15:40
@rjkennedy98 - we can use the statement "We run more than tens of thousand CORB jobs per day in our production" to market CoRB2. 

I haven't encountered SSL handshake issues in CorB, primarily because Aetna is probably the only project using this. However, in my previous we used to run into handshake problems due to intermittent network connectivity issues. This particular issues appeared to related to stream corruption, a flavor which we see in non-SSL environments as well. We used to see this quite a bit when we were using xcc 6 with ML 7, but not much these days. XCC should automatically retry some of these transactions automatically, but if not, you can always configure CorB 2.3.1 to do the same. The retry feature has been added to handle issues similar to these (intermittent or non-reproducible). 

However, please be cautions with updates. Since this is a network communication error, not necessarily a transaction failure, we need to check in the code if the update is already committed.

**Closed** 2016-08-19 11:56 UTC
Labels: wontfix
